version: '3'
services:
  test:
    build: test
    networks:
      test_network:
        ipv4_address: 10.0.1.78
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - tmp-driv:/var/run/aesmd
networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
    driver_opts:
      com.docker.network.bridge.name: test_network
volumes:
  tmp-driv:
    external: true